(defun swap (x y)
	(setf temp (aref arr x))
	(setf (aref arr x) (aref arr y))
	(setf (aref arr y) temp)
)
(write-line "Enter the number of values:")
(setq n (read))
(terpri)
(setf arr (make-array n))
(dotimes (i n)
	(setf (aref arr i) (read))
)
(do ((i 0 (+ i 1 ))) ((= i (- n 1)))
	(do ((j 0 (+ j 1))) ((= j (- (- n i) 1)))
		(if (> (aref arr j) (aref arr (+ j 1)))
			(swap j (+ j 1))
		)
	)
)
(terpri)
(write-line "The sorted values are:")
(terpri)
(dotimes (i n)
	(write (aref arr i))
	(write-line " ")
)